class Constants:
    APP_HOST = 'localhost'
    EXPIRED_DAY_NUMBER = 1
    ACCOUNT_TYPE_LOCAL = 'LOCAL'
    EXPIRED_HOURS_NUMBER = 24

    # Profile
    PROFILE_DEFAULT_FIRST_DAY_OF_WEEK = 'SU'
    PROFILE_DEFAULT_TIMEFORMAT = 'HH'
    PROFILE_DEFAULT_TIMEZONE = 'UTC'
    PROFILE_DEFAULT_LANGUAGE = 'EN'
    PROFILE_DEFAULT_DESCRIPTION = ''
    PROFILE_DEFAULT_AVATAR = 'Avatar'